FROM ruby:2.7.0-alpine3.11
MAINTAINER jhaffey2

# Setup working directory.
RUN mkdir -p /app
WORKDIR /app

# Install packages.
RUN apk update \
    && apk upgrade \
    && apk add build-base \
    && apk add nodejs \
    && apk add tzdata \
    && apk add libxslt-dev \
    && apk add libxml2-dev \
    && apk add sqlite-dev \
    && apk add git \
    && apk add yarn

# Install Rails & Bundler.
RUN gem install 'rails:6.0.2.1' 'bundler:2.1.4'

# Run a shell in the Rails env.
CMD ["/bin/sh"]
